version: '3.8'

services:
  csgo-analysis:
    build:
      context: ..
      dockerfile: docker_EGTA/Dockerfile
    container_name: csgo-abm-analysis
    volumes:
      - ..:/app
      - ../results:/mnt/hdd/csgo_abm
    environment:
      - PYTHONUNBUFFERED=1
    stdin_open: true
    tty: true
